# frozen_string_literal: true

source "https://rubygems.org"

platforms :ruby, :x64_mingw do
  gem "byebug", "~> 11.1"
  gem "colorize", "~> 0.8"
  gem "minitest", "~> 5.9"
  gem "minitest-reporters", "~> 1.4"
  gem "rake", "~> 13.0"
  gem "rubocop", "~> 1.12"
  gem "simplecov", "~> 0.20"
end


