language: node_js
node_js:
  - 3
  - 4
  - 5
  - 6.0
  - 6.1
  - 6.2
  - 6.3
  - 6.4
  - 6.5
  - 6.6
  - 7.7
before_script: cd js && npm install
script: npm run test-all
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
