language: node_js
node_js:
  - 0.6
  - 4.0
  - 5.0
  - 5.11
  - 6.0
  - 6.1
before_script: cd js && npm install
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
